### ISSUE TITLE
How to specify the topic and frame names?

### ISSUE THREAD

**Issue by wiku30** [koide3/hdl_localization#23]
In the hdl_graph_slam, I can change the topic and frame IDs (to run on data from other lidars) in the launch file. But in this project, I could not see interfaces about such IDs in the launch file.

So how to change the IDs?

**Comment by koide3** [comment]
Hi @wiku30 ,
You can remap "/velodyne_points" and "/gpsimu_driver/imu_data" topics to use this package with your sensor.

https://github.com/koide3/hdl_localization/blob/7e1dcdd7f0c8f7b042666c2730470ab6aa0a2945/apps/hdl_localization_nodelet.cpp#L50
https://github.com/koide3/hdl_localization/blob/7e1dcdd7f0c8f7b042666c2730470ab6aa0a2945/apps/hdl_localization_nodelet.cpp#L52

Maybe this packages should have more documentation so that users can tell how they can use it without taking look at the code... I'll put more information in README.

**Comment by wiku30** [comment]
Thanks!
